- nonebot/adapters/qqguild/adapter.py
> :bug: fix log level typo

- nonebot/adapters/qqguild/api/client.py
- nonebot/adapters/qqguild/api/handle.py
- nonebot/adapters/qqguild/api/model.py
- nonebot/adapters/qqguild/bot.py
- nonebot/adapters/qqguild/message.py
```python
from pathlib import Path
from nonebot import on_command
from nonebot.adapters.qqguild import MessageSegment
matcher = on_command("image")
@matcher.handle()
async def _():
msg = MessageSegment.file_image(Path("./example.png"))
await matcher.finish(msg)
```
> Feature: support local image

- nonebot/adapters/qqguild/api/handle.py
- nonebot/adapters/qqguild/bot.py
发送私信需要用 post_dms_messages ，且 post_dms_messages 返回值是 Message。
> Fix: 修复私信消息发送错误

- nonebot/adapters/qqguild/bot.py
- nonebot/adapters/qqguild/message.py
添加了 MessageSegment.reference。说起来有必要把这个命名为 MessageSegment.message_reference 吗？
> Feature: 支持 MessageReference

- nonebot/adapters/qqguild/message.py
> Feature: 支持 Mention Everyone

- nonebot/adapters/qqguild/adapter.py
- nonebot/adapters/qqguild/api/client.py
- nonebot/adapters/qqguild/api/request.py
- nonebot/adapters/qqguild/exception.py
- nonebot/adapters/qqguild/store.py
<https://bot.q.qq.com/wiki/develop/api/openapi/error/error.html#%E9%94%99%E8%AF%AF%E7%A0%81%E5%A4%84%E7%90%86>
>201,202	异步操作成功，虽然说成功，但是会返回一个 error body，需要特殊处理
添加一个 ResultStore，并在发送消息需要审核的时候报错。
> Feature: 添加 AuditException 并提供获取审核结果的方法

- nonebot/adapters/qqguild/api/model.py
> Feature: Message 添加 src_guild_id

- nonebot/adapters/qqguild/adapter.py
- nonebot/adapters/qqguild/bot.py
触发 on_connect 之前，先通过 ReadyEvent 设置相关信息。
> Fix: 连接 bot 前先设置相关信息

- nonebot/adapters/qqguild/event.py
这样应该就不会报错了。不过我只测试了 MESSAGE_DELETE 和 DIRECT_MESSAGE_DELETE。
close #38
> Feat: 支持 MessageDeleteEvent

- nonebot/adapters/qqguild/api/handle.py
> Fix: default value should be none not ellipsis

- nonebot/adapters/qqguild/bot.py
> Feature: 拆分消息发送到 send_to_dms 和 send_to 方法

- nonebot/adapters/qqguild/api/client.py
- nonebot/adapters/qqguild/api/handle.py
- nonebot/adapters/qqguild/api/model.py
- nonebot/adapters/qqguild/event.py
虽然API基本是残疾（
添加API（[API定义](https://bot.q.qq.com/wiki/develop/api/openapi/forum/model.html)）：
- get_threads
- get_thread
- put_thread
- delete_thread
添加事件（[事件定义](https://bot.q.qq.com/wiki/develop/api/gateway/forum.html)）：
- ForumEvent
- ForumThreadEvent
- ForumThreadCreateEvent
- ForumThreadUpdateEvent
- ForumThreadDeleteEvent
- ForumPostEvent
- ForumPostCreateEvent
- ForumPostDeleteEvent
- ForumReplyEvent
- ForumReplyCreateEvent
- ForumReplyDeleteEvent
- ForumPublishAuditResult
> Feature: 添加帖子模型、事件及API

- nonebot/adapters/qq/adapter.py
> Fix: 断开连接前确保机器人已连接

- nonebot/adapters/qq/bot.py
- nonebot/adapters/qq/message.py
- nonebot/adapters/qq/models/qq.py
> Feature: 支持群机器人 media 发送策略

- .devcontainer/devcontainer.json
- nonebot/adapters/qq/models/qq.py
> Fix: 修复群聊消息附件的字段类型错误

- nonebot/adapters/qq/message.py
> Feature: unescape plain text

- nonebot/adapters/qq/adapter.py
- nonebot/adapters/qq/event.py
- nonebot/adapters/qq/models/payload.py
> Feature: event 添加 payload id

- nonebot/adapters/qq/models/common.py
> Feature: 添加 ButtonInteraction 类型 13 内容

- nonebot/adapters/qq/bot.py
> Feature: 支持消息按钮事件被动回复

- nonebot/adapters/qq/message.py
> Feature: improve validator for `MessageSegment`

- nonebot/adapters/qq/models/qq.py
> Feature: add union openid to qq author

- nonebot/adapters/qq/adapter.py
- nonebot/adapters/qq/bot.py
> Fix: missing bot self info when using webhook

- nonebot/adapters/qq/bot.py
- nonebot/adapters/qq/message.py
> Fix: skip escape for qq

- nonebot/adapters/qq/models/guild.py
> Fix: 频道帖子可能不存在文字

- nonebot/adapters/qq/bot.py
私信发送主动消息时，会返回消息审核，并且`status_code`为200
> Fix: 更多情况的 Audit 捕获

- nonebot/adapters/qq/bot.py
> Feature: catch 200 error for access token

- nonebot/adapters/qq/bot.py
测试代码：<img width="1187" height="715" alt="image" src="https://github.com/user-attachments/assets/dc2c5d0f-e28a-4934-b070-453b5eddca6e" />
响应：
> Feature: 支持 `GroupAddRobotEvent` 事件发送消息
